In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
!pip install koreanize-matplotlib
plt.rcParams['axes.unicode_minus'] = False # - (마이너스)깨짐 방지
import koreanize_matplotlib
from google.colab import drive
drive.mount('/content/gdrive/')

Collecting koreanize-matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 17.9 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from koreanize-matplotlib) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)
Installing collected packages: koreanize-matplotlib
Successfully installed koreanize-matplotlib-0.1.1
Mounted at /content/gdrive/

In [2]:
distribution_centers = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/distribution_centers.csv')
events = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/events.csv')
order_items = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/order_items.csv')
inventory_items = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/inventory_items.csv')
orders = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/orders.csv')
products = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/products.csv')
users = pd.read_csv('/content/gdrive/MyDrive/the_look_ecommerce/thelook_users.csv')

In [3]:
# event기준으로 left join
merge_event_user = pd.merge(events, users,how = "left",left_on ='user_id',right_on ='id')
merge_event_user.rename(columns = {'id_x' : 'event_id'}, inplace = True)
merge_event_user.rename(columns = {'id_y' : 'user_origin_id'}, inplace = True)
merge_event_user.rename(columns = {'created_at_x' : 'event_created_at'}, inplace = True)
merge_event_user.rename(columns = {'created_at_y' : 'user_created_at'}, inplace = True)
merge_event_user.rename(columns = {'city_x' : 'event_city'}, inplace = True)
merge_event_user.rename(columns = {'city_y' : 'user_city'}, inplace = True)
merge_event_user.rename(columns = {'state_x' : 'event_state'}, inplace = True)
merge_event_user.rename(columns = {'state_y' : 'user_state'}, inplace = True)
merge_event_user.rename(columns = {'postal_code_x' : 'event_postal_code'}, inplace = True)
merge_event_user.rename(columns = {'postal_code_y' : 'user_postal_code'}, inplace = True)
merge_event_user.rename(columns = {'traffic_source_x' : 'event_traffic_source'}, inplace = True)
merge_event_user.rename(columns = {'traffic_source_y' : 'user_traffic_source'}, inplace = True)
merge_event_user

,event_id,user_id,sequence_number,session_id,event_created_at,ip_address,event_city,event_state,event_postal_code,browser,...,gender,user_state,street_address,user_postal_code,user_city,country,latitude,longitude,user_traffic_source,user_created_at
0,1917969,NaN,3,9395f670-3671-45f7-bb9a-9efc47b79c70,2022-09-12 06:21:00 UTC,129.52.135.73,São Paulo,São Paulo,02220-000,Chrome,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1922384,NaN,3,f0163a4c-f2c9-4b7d-ac17-705b55f7c657,2023-09-08 00:40:00 UTC,151.135.125.0,São Paulo,São Paulo,02220-000,Chrome,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1611526,NaN,3,2edc937a-699e-4285-b8eb-9817fd58a20c,2021-10-03 13:47:00 UTC,28.114.229.184,São Paulo,São Paulo,02675-031,Chrome,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1346381,NaN,3,4a399089-8d0a-4b82-9c28-7d5dca684610,2023-09-25 03:19:00 UTC,110.177.119.67,São Paulo,São Paulo,02675-031,Safari,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2167326,NaN,3,20c9ae70-07a6-4c08-a587-7c58058efe3a,2022-11-25 10:40:00 UTC,117.156.147.187,São Paulo,São Paulo,02675-031,Chrome,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2422917,1146027,88355.0,7,0beb4c6c-115c-48bd-ad91-a385ecf1b31c,2024-02-03 04:07:09 UTC,33.209.152.136,Timperley,England,WA15,Safari,...,M,England,008 Lindsey Drive Suite 867,WA15,Timperley,United Kingdom,53.373022,-2.316911,Search,2023-12-17 06:29:00 UTC
2422918,1199658,92597.0,10,30f540a1-bd8a-4b4e-8a5a-ace0d14eaa16,2022-07-22 09:23:07 UTC,166.94.222.219,Batley,England,WF17,Chrome,...,M,England,61021 Cameron Road,WF17,Batley,United Kingdom,53.724340,-1.640988,Search,2022-07-04 10:30:00 UTC
2422919,1028077,79178.0,10,7ac4c690-532f-475f-bf22-9f1ecaf4d7bb,2020-12-22 07:23:57 UTC,24.8.102.30,Orrell,England,WN5,Firefox,...,M,England,5771 Mark Place,WN5,Orrell,United Kingdom,53.524774,-2.696855,Search,2020-04-22 10:52:00 UTC
2422920,318852,24795.0,10,290090dd-c192-4bbb-ae40-5268a639dadf,2022-05-28 06:41:36 UTC,157.195.53.22,Abbots Bromley,England,WS15,Safari,...,M,England,002 Nielsen Lodge Suite 526,WS15,Abbots Bromley,United Kingdom,52.776999,-1.902598,Search,2020-12-19 08:12:00 UTC
2422921,23543,1866.0,5,dcdd215d-6ba0-4ab6-8d0e-ee5e14c1220b,2023-02-21 12:07:19 UTC,102.77.49.71,York,England,YO10,Firefox,...,M,England,652 Morgan Lakes Suite 149,YO10,York,United Kingdom,53.939925,-1.035756,Search,2021-02-08 13:14:00 UTC

In [4]:
events['created_at'] = pd.to_datetime(events['created_at'], errors='coerce')
##created_at  datetiem으로 type 변경
merge_event_user['event_created_at'] = pd.to_datetime(merge_event_user['event_created_at'], errors='coerce')
merge_event_user['user_created_at'] = pd.to_datetime(merge_event_user['user_created_at'], errors='coerce')

In [7]:
events['created_at'].min()

Timestamp('2019-01-02 00:01:00+0000', tz='UTC')

In [8]:
events['created_at'].max()

Timestamp('2024-06-14 15:05:10+0000', tz='UTC')

In [5]:
# Calculate WAU (Weekly Active Users)
dau = events.set_index('created_at').groupby(pd.Grouper(freq='D'))['user_id'].nunique()
wau = events.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['user_id'].nunique()

date_start = '2024-01-01'
date_end = '2024-06-10'


# 원하는 기간의 데이터만 추출
wau_recent = wau[date_start:date_end]


# 시각화
plt.figure(figsize=(12, 6))
plt.plot(wau_recent.index, wau_recent.values, marker='o', linestyle='-', color='b', label='2024년 WAU')


plt.title('2024 WAU)')
plt.xlabel('주')
plt.ylabel('Active User')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

KeyboardInterrupt:

In [ ]:
date_start = '2023-01-01'
date_end = '2023-12-31'


# 원하는 기간의 데이터만 추출
wau_recent = wau[date_start:date_end]


# 시각화
plt.figure(figsize=(12, 6))
plt.plot(wau_recent.index, wau_recent.values, marker='o', linestyle='-', color='b', label='2024년 WAU')


plt.title('2024 WAU)')
plt.xlabel('주')
plt.ylabel('Active User')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# 2023-2024 WAU 변화
date_start = '2023-01-01'
date_end = '2024-06-13'


# 원하는 기간의 데이터만 추출
wau_recent = wau[date_start:date_end]


# 시각화
plt.figure(figsize=(12, 6))
plt.plot(wau_recent.index, wau_recent.values, marker='o', linestyle='-', color='b', label='2023-2024 WAU')


plt.title('2023-2024 WAU')
plt.xlabel('주')
plt.ylabel('Active User')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
date_start = '2021-01-01'
date_end = '2022-12-31'


# 원하는 기간의 데이터만 추출
wau_recent = wau[date_start:date_end]


# 시각화
plt.figure(figsize=(12, 6))
plt.plot(wau_recent.index, wau_recent.values, marker='o', linestyle='-', color='b', label='2021-2022 WAU')


plt.title('2021-2022 WAU')
plt.xlabel('주')
plt.ylabel('Active User')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
date_start = '2019-01-01'
date_end = '2020-12-31'


# 원하는 기간의 데이터만 추출
wau_recent = wau[date_start:date_end]


# 시각화
plt.figure(figsize=(12, 6))
plt.plot(wau_recent.index, wau_recent.values, marker='o', linestyle='-', color='b', label='2019-2020 WAU')


plt.title('2019-2020 WAU')
plt.xlabel('주')
plt.ylabel('Active User')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# 연도별 평균 WAU 증가량 구하기
wau_yearly = wau.resample('Y').mean()

# 3. Calculate the annual average WAU increase
wau_yearly_increase = wau_yearly.diff().dropna()

# Optional: Convert the yearly average WAU to a DataFrame for better readability
wau_yearly_df = wau_yearly.reset_index()
wau_yearly_df.columns = ['year', 'average_wau']

wau_yearly_increase_df = wau_yearly_increase.reset_index()
wau_yearly_increase_df.columns = ['year', 'annual_increase']

# Display the results
print("연도별 평균 WAU:")
print(wau_yearly_df)
print("\n연도별 평균 WAU 증가:")
print(wau_yearly_increase_df)

In [ ]:
order_items['created_at'] = pd.to_datetime(order_items['created_at'], errors='coerce')
# Calculate WAU (Weekly Active Users)
weekly_order = order_items.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['order_id'].nunique()

weekly_order_yearly = weekly_order.resample('Y').mean()

weekly_order_increase = weekly_order_yearly.diff().dropna()
weekly_order_yearly_df = weekly_order_yearly.reset_index()
weekly_order_yearly_df.columns = ['year', 'average_order']

weekly_order_yearly_increase_df = weekly_order_increase.reset_index()
weekly_order_yearly_increase_df.columns = ['year', 'annual_increase']

# Display the results
print("연도별 평균 주문수:")
print(weekly_order_yearly_df)
print("\n연도별 평균 주문수 증가:")
print(weekly_order_yearly_increase_df)

In [ ]:
first_order_occurrence = order_items.groupby('order_id')['created_at'].min().reset_index()

# 2. Extract the year from 'created_at'
first_order_occurrence['year'] = first_order_occurrence['created_at'].dt.year

# 3. Count the number of unique orders per year
orders_per_year = first_order_occurrence.groupby('year')['order_id'].nunique().reset_index()
orders_per_year.columns = ['year', 'orders']

# Display the results
print("연도별 주문수:")
print(orders_per_year)

# 시각화
plt.figure(figsize=(10, 6))
plt.bar(orders_per_year['year'], orders_per_year['orders'], color='skyblue')
plt.xlabel('Year')
plt.ylabel('Number of Orders')
plt.title('연도별 주문수')
plt.xticks(orders_per_year['year'], rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
order_items['year'] = order_items['created_at'].dt.year

# 2. Calculate the total sales per year
sales_per_year = order_items.groupby('year')['sale_price'].sum().reset_index()
sales_per_year.columns = ['year', 'total_sales']

# Display the results
print("연도별 매출:")
print(sales_per_year)

# 시각화
plt.figure(figsize=(10, 6))
plt.bar(sales_per_year['year'], sales_per_year['total_sales'], color='skyblue')
plt.xlabel('Year')
plt.ylabel('총 매출')
plt.title('연도별 매출')
plt.xticks(sales_per_year['year'], rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
weekly_sale = order_items.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['sale_price'].sum()

# 2. Calculate the average weekly sales per year
weekly_sale_yearly = weekly_sale.resample('Y').mean()

# 3. Calculate the annual increase in average weekly sales
weekly_sale_increase = weekly_sale_yearly.diff().dropna()

# Convert the results to DataFrames for better readability
weekly_sale_yearly_df = weekly_sale_yearly.reset_index()
weekly_sale_yearly_df.columns = ['year', 'average_weekly_sales']

weekly_sale_yearly_increase_df = weekly_sale_increase.reset_index()
weekly_sale_yearly_increase_df.columns = ['year', 'annual_increase']

# Display the results
print("연도별 평균 매출:")
print(weekly_sale_yearly_df)
print("\n연도별 평균 매출 증가:")
print(weekly_sale_yearly_increase_df)

In [ ]:
weekly_sale = order_items.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['sale_price'].sum()
date_start = '2023-01-01'
date_end = '2024-06-13'

# 원하는 기간의 데이터만 추출
weekly_sale_recent = weekly_sale[date_start:date_end]

# 시각화
plt.figure(figsize=(12, 6))
plt.plot(weekly_sale_recent.index, weekly_sale_recent.values, marker='o', linestyle='-', color='b', label='2023-2024 매출')


plt.title('2023-2024 매출')
plt.xlabel('주')
plt.ylabel('매출')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
weekly_sale = order_items.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['sale_price'].sum()
date_start = '2021-01-01'
date_end = '2022-12-31'

# 원하는 기간의 데이터만 추출
weekly_sale_recent = weekly_sale[date_start:date_end]

# 시각화
plt.figure(figsize=(12, 6))
plt.plot(weekly_sale_recent.index, weekly_sale_recent.values, marker='o', linestyle='-', color='b', label='2021-2022 매출')


plt.title('2021-2022 매출')
plt.xlabel('주')
plt.ylabel('매출')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
weekly_sale = order_items.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['sale_price'].sum()
date_start = '2019-01-01'
date_end = '2020-12-31'

# 원하는 기간의 데이터만 추출
weekly_sale_recent = weekly_sale[date_start:date_end]

# 시각화
plt.figure(figsize=(12, 6))
plt.plot(weekly_sale_recent.index, weekly_sale_recent.values, marker='o', linestyle='-', color='b', label='2019-2020 매출')


plt.title('2019-2020 매출')
plt.xlabel('주')
plt.ylabel('매출')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
users['created_at'] = pd.to_datetime(users['created_at'], errors='coerce')
# Calculate WAU (Weekly Active Users)
weekly_user = users.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['id'].nunique()

weekly_user_yearly = weekly_user.resample('Y').mean()

weekly_user_increase = weekly_user_yearly.diff().dropna()
weekly_user_yearly_df = weekly_user_yearly.reset_index()
weekly_user_yearly_df.columns = ['year', 'average_user_num']

weekly_user_yearly_increase_df = weekly_user_increase.reset_index()
weekly_user_yearly_increase_df.columns = ['year', 'annual_increase']

# Display the results
print("연도별 평균 user수:")
print(weekly_user_yearly_df)
print("\n연도별 평균 user수 증가:")
print(weekly_user_yearly_increase_df)

In [ ]:
first_appearance = users.groupby('id')['created_at'].min().reset_index()

# 2. Group these first appearances by year to count the number of new users each year
first_appearance['year'] = first_appearance['created_at'].dt.year
new_users_per_year = first_appearance.groupby('year')['id'].nunique().reset_index()
new_users_per_year.columns = ['year', 'new_users']

# Display the results
print("연도별 신규 user수:")
print(new_users_per_year)

In [ ]:
inventory_items.nunique()

In [ ]:
first_inventory_items = inventory_items.groupby('id')['created_at'].min().reset_index()

# 2. Extract the year from 'created_at'
first_inventory_items['year'] = first_inventory_items['created_at'].dt.year

# 3. Count the number of new inventory items per year
new_inventory_items_per_year = first_inventory_items.groupby('year')['id'].nunique().reset_index()
new_inventory_items_per_year.columns = ['year', 'new_inventory_items']

# Display the results
print("연도별 신규 입고 물품수:")
print(new_inventory_items_per_year)

In [ ]:
inventory_items['created_at'] = pd.to_datetime(inventory_items['created_at'], errors='coerce')

# 1. Calculate the total sales per week
weekly_inventory_items = inventory_items.set_index('created_at').groupby(pd.Grouper(freq='W-MON'))['product_id'].sum()

# 2. Calculate the average weekly sales per year
weekly_inventory_items_yearly = weekly_inventory_items.resample('Y').mean()

# 3. Calculate the annual increase in average weekly sales
weekly_inventory_items_increase = weekly_inventory_items_yearly.diff().dropna()

# Convert the results to DataFrames for better readability
weekly_inventory_items_yearly_df = weekly_inventory_items_yearly.reset_index()
weekly_inventory_items_yearly_df.columns = ['year', 'average_weekly_inventory_items']

weekly_inventory_items_yearly_increase_df = weekly_inventory_items_increase.reset_index()
weekly_inventory_items_yearly_increase_df.columns = ['year', 'annual_increase']

# Display the results
print("연도별 평균 매출:")
print(weekly_inventory_items_yearly_df)
print("\n연도별 평균 매출 증가:")
print(weekly_inventory_items_yearly_increase_df)